// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARJNT8hq4uBUJg-KmenAEL44l35kVsjLg',
    appId: '1:659028778441:web:6b2865f7efc1e7000f9c18',
    messagingSenderId: '659028778441',
    projectId: 'nofi-6a606',
    authDomain: 'nofi-6a606.firebaseapp.com',
    storageBucket: 'nofi-6a606.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKlr_tjQPedU0KWqPc_V2mjVfj2iy7HCM',
    appId: '1:659028778441:android:d79660b3772a34740f9c18',
    messagingSenderId: '659028778441',
    projectId: 'nofi-6a606',
    storageBucket: 'nofi-6a606.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQjDJTTA6KvmHiEKSTpWsesmqQ7XtHtog',
    appId: '1:659028778441:ios:23f2c23c2bc751c30f9c18',
    messagingSenderId: '659028778441',
    projectId: 'nofi-6a606',
    storageBucket: 'nofi-6a606.appspot.com',
    iosClientId: '659028778441-01188in2uet6s6jusj9n9a3ac8ukr652.apps.googleusercontent.com',
    iosBundleId: 'com.example.notfi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQjDJTTA6KvmHiEKSTpWsesmqQ7XtHtog',
    appId: '1:659028778441:ios:23f2c23c2bc751c30f9c18',
    messagingSenderId: '659028778441',
    projectId: 'nofi-6a606',
    storageBucket: 'nofi-6a606.appspot.com',
    iosClientId: '659028778441-01188in2uet6s6jusj9n9a3ac8ukr652.apps.googleusercontent.com',
    iosBundleId: 'com.example.notfi',
  );
}
